### ISSUE TITLE
TODO add to api

### ISSUE THREAD

**Issue by petterroea** [InfectedLan/InfectedCompo#1]
- [x] Table/Object clan. ID, Chief, Name, Event
- [x] Table memberof. ID, userid, clanid
- [x] Table invites. ID, userid, clanid
- [x] Modify compo. ID, StartTime, RegistrationEnd, Name, desc
- [x] Table participantOf.(Clan participating in X compo). ID, clanId, CompoId
- [x] VoteOption. ID, CompoId, Thumbnail, Name
- [x] Votes. Id, UserId, VoteOption
